### ISSUE TITLE
is.plainObject returns false even when both objects are same

### ISSUE THREAD

**Issue by not-john-wick** [gilbarbara/is-lite#12]
I am currently using react-joyride in my current project, and I am facing an issue when starting the tour. The application fails with with error _Error: Expected plain objects or array_. Upon investigation I found that is.plainObject method of is-lite library is returning false even when both the objects are similar.

Specifically the comparison **prototype === Object.getPrototypeOf({})** https://github.com/gilbarbara/is-lite/blob/main/src/index.ts#L233-L235 is returning false.

Issue occurs during react-joyride: step:0 and while comparing previousProps with this.props. Unfortunately I can not share the code where this issue is coming because of company's privacy policy. But please let me know what other information I can provide.

Interestingly if I create a standalone project and use react-joyride there, everything works fine.

Can it be related to polyfills?

**Comment by gilbarbara** [comment]
Hey @not-john-wick 
Not sure I get what you mean by "**returns false even when both objects are same**" as this library doesn't compare values.
You likely passed a non-standard object since a basic project works, as you mentioned.

Anyway, without code examples, there's nothing I can't do.
