### ISSUE TITLE
is.nan breaks in legacy browsers

### ISSUE THREAD

**Issue by tomchentw** [gilbarbara/is-lite#4]
Hi, came from `react-joyride` and it throws on IE11, which traced back to `is.nan`:

https://github.com/gilbarbara/is-lite/blob/v0.6.0/src/index.ts#L163-L165

`Number` don't have the `isNaN` function defined in legacy browsers.

---

**Question**

Are you willing to support legacy browsers? Guess that might against your intention of having this package.

**Comment by gilbarbara** [comment]
hey

You can load a polyfill if you need to support legacy browsers.
