### ISSUE TITLE
Cannot find source file '../src/index.ts'

### ISSUE THREAD

**Issue by MasterVitte** [gilbarbara/is-lite#6]
Hi! I've installed is-lite library using npm and have an error: `Can't resolve '../src/index.ts'.` Version 0.7.0.
Updated: I think react-joyride has the dependence problem (third screen). React-floater has same problem.

![image](https://user-images.githubusercontent.com/54363060/92091878-06be2700-edda-11ea-886a-080d45000fd5.png)

![image](https://user-images.githubusercontent.com/54363060/92091919-12a9e900-edda-11ea-94e7-270ea28e1ea4.png)

![image](https://user-images.githubusercontent.com/54363060/92092635-04100180-eddb-11ea-9776-d7f99762a87c.png)

**Comment by gilbarbara** [comment]
hey @MasterVitte 

Sorry for the late reply. It didn't show in notifications...

I've never seen this error, can you try to reproduce it in a codesandbox?

Thanks

**Comment by brionmario** [comment]
We are also experiencing this issue in our project. Will try to come up with a reproduction.

```
WARNING in ./node_modules/react-floater/node_modules/is-lite/lib/index.js
Module Warning (from ../../node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../src/index.ts': Error: Can't resolve '../src/index.ts' in '<PROJECT>/node_modules/react-floater/node_modules/is-lite/lib'
 @ ./node_modules/react-floater/es/index.js 8:0-25 217:12-26 558:47-60 741:26-40 935:10-23 959:10-23 983:10-23 1049:24-37 1057:34-47 1076:12-25 1189:29-41 1238:11-23 1391:12-25
 @ ./node_modules/react-joyride/es/index.js 13:0-36 2508:45-52
```
