### ISSUE TITLE
Number.isNan is not supported in IE11

### ISSUE THREAD

**Issue by Dvvarf** [gilbarbara/is-lite#7]
It would be nice to put a note somewhere, that IE is not supported by this library, because of these lines:
https://github.com/gilbarbara/is-lite/blob/6b60914fd6c563561de4b29840a3e8f789cb4c7e/src/index.ts#L160-L162

Number.isNaN is [not supported by IE](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN#Browser_compatibility).

**Comment by gilbarbara** [comment]
hey @Dvvarf 

You can use a polyfill for that!

**Comment by Dvvarf** [comment]
I've only posted this issue here because this library is used by react-joyride and that, in turn claims ie11 compatibility.

Also I was asking to put a note about ie11 support, not to fix it or asking how to fix it.

**Comment by gilbarbara** [comment]
Where did you read that IE11 compatibility claims on React joyride? I couldn't find it.

**Comment by Dvvarf** [comment]
OK, it's not exactly claiming ie11 compatibility, but readme has the following sentence: "If you need to support legacy browsers you need to include the scrollingelement polyfill."
I'll open an issue with them asking to change this note,since it's not correct anymore. Thanks.

**Comment by gilbarbara** [comment]
There's no need, I'll drop IE 11 support completely in the upcoming react-joyride version.
